[theme]
primaryColor = "#FF4B4B"          # Buttons, highlights
backgroundColor = "#F5F5F5"       # Main background
secondaryBackgroundColor = "#FFFFFF" # Sidebar background
textColor = "#262730"             # Text color
font = "sans serif"               # Options: "sans serif", "serif", "monospace"
